insert  into `negaras`(`id`,`nama`,`kode`) values
(1, 'Afganistan', 'AF'),
(2, 'Afrika Selatan', 'ZA'),
(3, 'Albania', 'AL'),
(4, 'Algeria', 'DZ'),
(5, 'Amerika Serikat', 'US'),
(6, 'Andorra', 'AD'),
(7, 'Angola', 'AO'),
(8, 'Antigua dan Barbuda', 'AG'),
(9, 'Arab Saudi', 'SA'),
(10, 'Argentina', 'AR'),
(11, 'Armenia', 'AM'),
(12, 'Australia', 'AU'),
(13, 'Austria', 'AT'),
(14, 'Azerbaijan', 'AZ'),
(15, 'Bahama', 'BS'),
(16, 'Bahrain', 'BH'),
(17, 'Bangladesh', 'BD'),
(18, 'Barbados', 'BB'),
(19, 'Belanda', 'NL'),
(20, 'Belize', 'BZ'),
(21, 'Benin', 'BJ'),
(22, 'Bhutan', 'BT'),
(23, 'Bolivia', 'BO'),
(24, 'Bosnia dan Herzegovina', 'BA'),
(25, 'Botswana', 'BW'),
(26, 'Brasil', 'BR'),
(27, 'Brunei Darussalam', 'BN'),
(28, 'Bulgaria', 'BG'),
(29, 'Burkina Faso', 'BF'),
(30, 'Burundi', 'BI'),
(31, 'Butswana', 'BW'),
(32, 'Ceko', 'CZ'),
(33, 'Chile', 'CL'),
(34, 'Cina', 'CN'),
(35, 'Cyprus', 'CY'),
(36, 'Denmark', 'DK'),
(37, 'Djibouti', 'DJ'),
(38, 'Dominika', 'DM'),
(39, 'Dominika', 'DO'),
(40, 'Ekuador', 'EC'),
(41, 'El Salvador', 'SV'),
(42, 'Eritrea', 'ER'),
(43, 'Eswatini', 'SZ'),
(44, 'Estonia', 'EE'),
(45, 'Ethiopia', 'ET'),
(46, 'Fiji', 'FJ'),
(47, 'Filipina', 'PH'),
(48, 'Finlandia', 'FI'),
(49, 'Gabon', 'GA'),
(50, 'Gambia', 'GM'),
(51, 'Georgia', 'GE'),
(52, 'Ghana', 'GH'),
(53, 'Grenada', 'GD'),
(54, 'Guatemala', 'GT'),
(55, 'Guinea', 'GN'),
(56, 'Guinea-Bissau', 'GW'),
(57, 'Guyana', 'GY'),
(58, 'Haiti', 'HT'),
(59, 'Honduras', 'HN'),
(60, 'Hong Kong', 'HK'),
(61, 'Hungaria', 'HU'),
(62, 'India', 'IN'),
(63, 'Indonesia', 'ID'),
(64, 'Irak', 'IQ'),
(65, 'Iran', 'IR'),
(66, 'Irlandia', 'IE'),
(67, 'Israel', 'IL'),
(68, 'Italia', 'IT'),
(69, 'Jamaika', 'JM'),
(70, 'Jepang', 'JP'),
(71, 'Jordania', 'JO'),
(72, 'Juba', 'SS'),
(73, 'Jumhuriyah Rakyat Demokratik Korea', 'KP'),
(74, 'Juni', 'KR'),
(75, 'Kamerun', 'CM'),
(76, 'Kanada', 'CA'),
(77, 'Kepulauan Cook', 'CK'),
(78, 'Kepulauan Marshall', 'MH'),
(79, 'Kepulauan Solomon', 'SB'),
(80, 'Kepulauan Virgin Britania Raya', 'VG'),
(81, 'Kirgistan', 'KG'),
(82, 'Kiribati', 'KI'),
(83, 'Kolombia', 'CO'),
(84, 'Komoros', 'KM'),
(85, 'Kongo (Republik Kongo)', 'CG'),
(86, 'Kongo (Republik Demokratik Kongo)', 'CD'),
(87, 'Korea Selatan', 'KR'),
(88, 'Korea Utara', 'KP'),
(89, 'Kosta Rika', 'CR'),
(90, 'Kuba', 'CU'),
(91, 'Kuwait', 'KW'),
(92, 'Laos', 'LA'),
(93, 'Lesotho', 'LS'),
(94, 'Latvia', 'LV'),
(95, 'Lebanon', 'LB'),
(96, 'Lesotho', 'LS'),
(97, 'Liberia', 'LR'),
(98, 'Libya', 'LY'),
(99, 'Liechtenstein', 'LI'),
(100, 'Lituania', 'LT'),
(101, 'Luxembourg', 'LU'),
(102, 'Madagaskar', 'MG'),
(103, 'Maladewa', 'MV'),
(104, 'Malawi', 'MW'),
(105, 'Malaysia', 'MY'),
(106, 'Malta', 'MT'),
(107, 'Maroko', 'MA'),
(108, 'Marshall Islands', 'MH'),
(109, 'Mauritania', 'MR'),
(110, 'Mauritius', 'MU'),
(111, 'Meksiko', 'MX'),
(112, 'Mikronesia', 'FM'),
(113, 'Moldova', 'MD'),
(114, 'Monako', 'MC'),
(115, 'Mongolia', 'MN'),
(116, 'Montenegro', 'ME'),
(117, 'Mozambik', 'MZ'),
(118, 'Myanmar', 'MM'),
(119, 'Namibia', 'NA'),
(120, 'Nauru', 'NR'),
(121, 'Nepal', 'NP'),
(122, 'Niger', 'NE'),
(123, 'Nigeria', 'NG'),
(124, 'Nikaragua', 'NI'),
(125, 'Norwegia', 'NO'),
(126, 'Nugini', 'PG'),
(127, 'Oman', 'OM'),
(128, 'Pakistan', 'PK'),
(129, 'Palau', 'PW'),
(130, 'Panama', 'PA'),
(131, 'Papua Nugini', 'PG'),
(132, 'Paraguay', 'PY'),
(133, 'Peru', 'PE'),
(134, 'Polandia', 'PL'),
(135, 'Portugal', 'PT'),
(136, 'Qatar', 'QA'),
(137, 'Republik Ceko', 'CZ'),
(138, 'Republik Kongo', 'CG'),
(139, 'Republik Dominika', 'DO'),
(140, 'Rumania', 'RO'),
(141, 'Rusia', 'RU'),
(142, 'Rwanda', 'RW'),
(143, 'Saint Kitts dan Nevis', 'KN'),
(144, 'Saint Lucia', 'LC'),
(145, 'Saint Vincent dan Grenadines', 'VC'),
(146, 'Samoa', 'WS'),
(147, 'San Marino', 'SM'),
(148, 'Sao Tome dan Principe', 'ST'),
(149, 'Saudi Arabia', 'SA'),
(150, 'Senegal', 'SN');
